import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

import RegisterModal from "@/components/modals/RegisterModal";
import ToasterProvider from "./providers/ToasterProvider";
import LoginModal from "@/components/modals/LoginModal";
import getCurrentUser from "./actions/getCurrentUser";
import ClientOnly from "@/components/ClientOnly";
import RentModal from "@/components/modals/RentModal";
import MapProvider from "@/components/MapProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});




export const metadata: Metadata = {
  title: "Selam Millet",
  description: "Generated by create next app",
};
const nunito = Nunito({
  
  subsets: ["latin"]})

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const currentUser=await getCurrentUser()
  return (
    <html lang="en">
      <body
        className={nunito.className}
      >

        <ToasterProvider/>
    
        <LoginModal/>
        <RegisterModal/>
        <RentModal/>
        <ClientOnly>
        <Navbar currentuser={currentUser}/>
        </ClientOnly>
         <MapProvider> {/* 👈 Wrap edilen alan */}
          <div className="pb-20 pt-28">{children}</div>
        </MapProvider>
      </body>
    </html>
  );
}
